#Compiler info
CC=gcc
#Flags used during compilation
CFLAGS=-Wall
#target: dependency file(s) or third-party libraries
main: main.o array.o
#Perform cleanup activities
clean:
	rm -f main main.o array.o
