#Compiler info
CC=gcc
#Flags used during compilation
CFLAGS=-Wall -g 
#target: dependency file(s) or third-party libraries
struct_prg: struct_prg.o struct.o
#Perform cleanup activities
clean:
	rm -f main struct_prg.o struct.o
