#Compiler info
CC=gcc
#Flags used during compilation
CFLAGS=-Wall -g 
#target: dependency file(s) or third-party libraries
main: main.o ptr.o
#Perform cleanup activities
clean:
	rm -f main main.o ptr.o
